function panelplot(model, T_true, T_pred, true_name, pred_name)

fig = figure;
fig.Position = [0, 0, 500, 1000]

subplot(3,1,1);
pdeplot(...
    model, ...
    'XYData', T_true, ...
    'ZData',  T_true, ...
    'Contour',  'on', ...
    'ColorMap', 'hot' ...
);
view([0 0 1]); axis tight;

true_name
title(sprintf('True temperature (%s)', true_name));

subplot(3,1,2);
pdeplot(...
    model, ...
    'XYData', T_pred, ...
    'ZData',  T_pred, ...
    'Contour',  'on', ...
    'ColorMap', 'hot' ...
);
view([0 0 1]); axis tight;

pred_name
title(sprintf('Predicted temperature (%s)', pred_name));

subplot(3,1,3);
pdeplot(...
    model, ...
    'XYData', T_true - T_pred, ...
    'ZData',  T_true - T_pred, ...
    'Contour',  'on', ...
    'ColorMap', 'hot' ...
);
view([0 0 1]); axis tight;

error = sum((T_true - T_pred).^2, 'all')
rel_error = error / sum(T_true.^2, 'all') * 100

title(sprintf('Error (abs = %.2e, rel = %.2f\\%%)', error, rel_error));
